ui: tape
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
scripts:
  - './node_modules/pouchdb/dist/pouchdb.js'
  - './node_modules/pouchdb/dist/pouchdb.memory.js'
