'use strict'

require('./specs/factory')
require('./specs/add')
require('./specs/find')
require('./specs/find-all')
require('./specs/find-or-add')
require('./specs/update')
require('./specs/update-or-add')
require('./specs/update-all')
require('./specs/remove')
require('./specs/remove-all')
require('./specs/clear')
require('./specs/events')
require('./specs/with-id-prefix')
