'use strict'

require('./integration/factory')
require('./integration/add')
require('./integration/find')
require('./integration/find-all')
require('./integration/find-or-add')
require('./integration/update')
require('./integration/update-or-add')
require('./integration/update-all')
require('./integration/remove')
require('./integration/remove-all')
require('./integration/clear')
require('./integration/events')
require('./integration/with-id-prefix')
